- job_name: 'kubernetes_components'
      kubernetes_sd_configs:
      - api_servers:
          'https://kubernetes.default.svc'
      in_cluster: true
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
        - source_labels: [__meta_kubernetes_role]
          action: keep
          regex: (?:apiserver|node)
        - source_labels: [__meta_kubernetes_role]
          target_label: job
          replacement: kubernetes_$1
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)

- name: Pods
        rules:
        - alert: Container restarted
          annotations:
            summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} was restarted
          expr: |
            sum(increase(kube_pod_container_status_restarts_total{namespace!="kube-system",pod_template_hash=""}[1m])) by (pod,namespace,container) > 0
          for: 0m
      - name: Nodes
        rules:
        - alert: high_cpu_load
        expr: node_load1 > 0.1
        for: 3s
        labels:
          severity: warning
        annotations:
        summary: "Server under high load"
        description: "Cpu host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

