---
- hosts: k8s-master
  become: yes
  gather_facts: false
  tasks:
  - name: get join cmd
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join cmd
    set_fact: 
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks: 
  - name: join cluster
    shell: "{{ hostvars['k8s-master'].join_command }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt
