kind: PersistentVolume
apiVersion: v1
metadata:
  name: registry-volume
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/registry/"

