kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-pvc
  namespace: dev
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
