kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastic-storage-volume
  namespace: logging
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elastic/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastic-claim
  namespace: logging
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
