kind: PersistentVolume
apiVersion: v1
metadata:
  name: influx-storage-volume
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/influx/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influx-claim
  namespace: monitoring
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
