kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-storage-volume
  namespace: monitoring
  labels:
    type: local
    app: prometheus-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus/"

