kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-storage-volume
  namespace: gitlab
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/gitlab/gitlab-app"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-claim
  namespace: gitlab
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

