apiVersion: v1
kind: Service
metadata:
  name: gitlab-app
  namespace: gitlab
  labels:
    name: gitlab-app
    app: gitlab
spec:
  selector:
    name: gitlab-app
  ports:
    - name: http
      port: 8005
      targetPort: http
    - name: ssh
      port: 22
      targetPort: ssh

